"""Constants for Sensirion SHT31 BLE."""

DOMAIN = "sensirion_sht31_ble"

CONF_BATTERY_POLL_INTERVAL = "battery_poll_interval"
CONF_STALENESS_TIMEOUT = "staleness_timeout"

DEFAULT_BATTERY_POLL_INTERVAL = 600
DEFAULT_STALENESS_TIMEOUT = 120

UNAVAILABLE_GRACE_PERIOD = 30
